
const STATUS_REQUESTING_VIDEO = 9000001
const STATUS_REQUESTING_VIDEO_FAILED = 9000002
const STATUS_INTERRUPT_TRYING_TO_RECONNECT_VIDEO = 9000003
const STATUS_RECONNECT_VIDEO = 9000004
const STATUS_TALKING_VIDEO = 9000005

export default {
  STATUS_REQUESTING_VIDEO,
  STATUS_REQUESTING_VIDEO_FAILED,
  STATUS_INTERRUPT_TRYING_TO_RECONNECT_VIDEO,
  STATUS_RECONNECT_VIDEO,
  STATUS_TALKING_VIDEO
}

